title: Daniyal Nawaz | Computer Engineer
email: 2025bscpe144@gmail.com
description: A Computer Engineering student at UET Lahore, Faisalabad Campus documenting my journey.
baseurl: ""
url: https://github.com/2025bscpe144-eng

author: Daniyal

theme: minima

plugins:
  - jekyll-feed
